version: '2'
services:
  node:
    image: "node:16"
    user: "node"
    working_dir: /var/www/html
    environment:
      - NODE_ENV=dev
    volumes:
      - ./project:/var/www/html:rw
    ports:
      - "3000:3000"
    command: "npm start"
